export const DEFAULT_COMPLIANCE_STANDARDS = [
  {
    standardKey: "ICH_Q7_CFR21",
    version: "1.0.0",
    name: "ICH Q7 + 21 CFR Part 210/211",
    description:
      "Baseline GMP controls mapped for pharmaceutical supplier audits.",
    domain: "GMP",
    scope: "TENANT",
    status: "ACTIVE",
    controls: [
      {
        controlId: "FACILITY_QUALIFICATION",
        title: "Facility and Area Qualification",
        description:
          "Manufacturing and storage areas must be suitable and controlled.",
        clauseRef: "ICH Q7 4.12",
        standardRefs: ["21 CFR 211.42", "21 CFR 211.46"],
        keywords: [
          "facility",
          "premises",
          "area",
          "warehouse",
          "cleaning",
          "layout",
        ],
        expectedAnswer: "YES",
        requiredEvidence: true,
        weight: 1.2,
      },
      {
        controlId: "DOCUMENT_CONTROL",
        title: "Document and Record Control",
        description: "SOPs, forms, and records should be current and controlled.",
        clauseRef: "ICH Q7 6.1",
        standardRefs: ["21 CFR 211.100", "21 CFR 211.180"],
        keywords: ["sop", "record", "document", "revision", "approval", "log"],
        expectedAnswer: "YES",
        requiredEvidence: true,
        weight: 1.3,
      },
      {
        controlId: "TRAINING_COMPETENCY",
        title: "Training and Competency",
        description:
          "Personnel must be trained, qualified, and periodically assessed.",
        clauseRef: "ICH Q7 3.1",
        standardRefs: ["21 CFR 211.25"],
        keywords: [
          "training",
          "competency",
          "qualified",
          "personnel",
          "induction",
        ],
        expectedAnswer: "YES",
        requiredEvidence: false,
        weight: 1.0,
      },
      {
        controlId: "CHANGE_CONTROL_CAPA",
        title: "Change Control and CAPA",
        description:
          "Changes, deviations, and CAPA should be managed with root cause analysis.",
        clauseRef: "ICH Q7 13.1",
        standardRefs: ["21 CFR 211.100", "21 CFR 211.192"],
        keywords: [
          "change control",
          "deviation",
          "capa",
          "root cause",
          "corrective",
        ],
        expectedAnswer: "YES",
        requiredEvidence: false,
        weight: 1.15,
      },
      {
        controlId: "VALIDATION_PROGRAM",
        title: "Validation Program",
        description:
          "Validation and qualification should be defined, executed, and maintained.",
        clauseRef: "ICH Q7 12.1",
        standardRefs: ["21 CFR 211.68", "21 CFR 211.110"],
        keywords: [
          "validation",
          "qualification",
          "protocol",
          "report",
          "equipment",
          "process",
        ],
        expectedAnswer: "YES",
        requiredEvidence: true,
        weight: 1.25,
      },
      {
        controlId: "DATA_INTEGRITY",
        title: "Data Integrity",
        description:
          "Data should be attributable, legible, contemporaneous, original, and accurate.",
        clauseRef: "ICH Q7 6.5",
        standardRefs: ["21 CFR 211.194", "21 CFR 211.68"],
        keywords: [
          "data integrity",
          "audit trail",
          "alcoa",
          "electronic record",
          "backup",
        ],
        expectedAnswer: "YES",
        requiredEvidence: false,
        weight: 1.1,
      },
    ],
    metadata: {
      source: "builtin",
      noCost: true,
      notes: "Deterministic matching pack. Extend controls to support tenant use-cases.",
    },
  },
  {
    standardKey: "ISO9001_QMS",
    version: "2015.1",
    name: "ISO 9001:2015 Quality Management System",
    description:
      "General QMS controls for supplier qualification and periodic surveillance.",
    domain: "QUALITY",
    scope: "TENANT",
    status: "ACTIVE",
    controls: [
      {
        controlId: "QMS_CONTEXT",
        title: "Context of Organization and Scope",
        description:
          "Organization context, scope, and interested parties are defined.",
        clauseRef: "ISO 9001 4.1-4.3",
        standardRefs: ["ISO 9001:2015 4.1", "ISO 9001:2015 4.3"],
        keywords: ["scope", "context", "qms", "interested parties", "boundary"],
        expectedAnswer: "YES",
        requiredEvidence: false,
        weight: 1.0,
      },
      {
        controlId: "RISK_BASED_THINKING",
        title: "Risk-Based Thinking",
        description: "Risks and opportunities are identified and addressed.",
        clauseRef: "ISO 9001 6.1",
        standardRefs: ["ISO 9001:2015 6.1"],
        keywords: ["risk", "opportunity", "mitigation", "assessment", "register"],
        expectedAnswer: "YES",
        requiredEvidence: false,
        weight: 1.05,
      },
      {
        controlId: "DOCUMENTED_INFORMATION",
        title: "Documented Information",
        description: "Documents and records are controlled and retrievable.",
        clauseRef: "ISO 9001 7.5",
        standardRefs: ["ISO 9001:2015 7.5"],
        keywords: ["document", "record", "retention", "revision", "controlled copy"],
        expectedAnswer: "YES",
        requiredEvidence: true,
        weight: 1.1,
      },
      {
        controlId: "MONITORING_MEASUREMENT",
        title: "Monitoring and Measurement",
        description:
          "Processes are monitored with metrics, reviews, and improvement actions.",
        clauseRef: "ISO 9001 9.1",
        standardRefs: ["ISO 9001:2015 9.1"],
        keywords: ["kpi", "monitor", "measurement", "trend", "review", "improvement"],
        expectedAnswer: "YES",
        requiredEvidence: false,
        weight: 1.0,
      },
    ],
    metadata: {
      source: "builtin",
      noCost: true,
    },
  },
];

