export const AUDIT_MODULES = ["cGMP", "EQMS", "EHQS", "SAFETY"];

export const AUDIT_PHASE_KEYS = {
  PREP: "PREP",
  SCOPE_AGENDA: "SCOPE_AGENDA",
  SCHEDULING: "SCHEDULING",
  EXECUTION: "EXECUTION",
  REPORTING: "REPORTING",
  FOLLOWUP_CAPA: "FOLLOWUP_CAPA",
};

export const AUDIT_PHASE_ORDER = [
  AUDIT_PHASE_KEYS.PREP,
  AUDIT_PHASE_KEYS.SCOPE_AGENDA,
  AUDIT_PHASE_KEYS.SCHEDULING,
  AUDIT_PHASE_KEYS.EXECUTION,
  AUDIT_PHASE_KEYS.REPORTING,
  AUDIT_PHASE_KEYS.FOLLOWUP_CAPA,
];

export const PHASE_STATUSES = ["NOT_STARTED", "IN_PROGRESS", "BLOCKED", "DONE"];
export const MILESTONE_STATUSES = ["NOT_STARTED", "IN_PROGRESS", "BLOCKED", "DONE"];

export const ASSESSMENT_TYPES = ["External", "Internal", "Surveillance", "Self"];
export const ASSESSMENT_STATUSES = ["DRAFT", "ACTIVE", "COMPLETED", "ARCHIVED"];

export const QUESTIONNAIRE_KINDS = ["PRE_AUDIT", "FULL"];
export const QUESTIONNAIRE_STATUSES = [
  "DRAFT",
  "SENT",
  "IN_PROGRESS",
  "SUBMITTED",
  "REVIEWED",
  "CLOSED",
  "WAIVED",
];

export const STANDARD_DOMAINS = ["QUALITY", "EHS", "GMP", "SAFETY"];
