// Quick seed script to create sample CAPAs per tenant for local testing.
// Usage: node scripts/seed_capas.js
import dotenv from "dotenv";
import mongoose from "mongoose";
import { Capa } from "../src/models/capaModel.js";
import { AuditRequestMaster } from "../src/models/auditRequestsMasterModel.js";

dotenv.config();

const MONGO_URI = process.env.MONGO_URI || process.env.DB_URL || "mongodb://localhost:27017/hawkeye";

async function seed() {
  await mongoose.connect(MONGO_URI);
  console.log("Connected to Mongo");

  const audits = await AuditRequestMaster.find().limit(5);
  if (!audits.length) {
    console.warn("No audits found; skipping CAPA seed.");
    return;
  }

  const docs = audits.map((audit, idx) => ({
    tenantOrgId: audit.tenantOrgId || null,
    auditId: audit._id,
    buyerId: audit.create_by_buyer_id,
    auditorId: audit.auditor_id,
    supplierId: audit.supplier_id,
    title: `Seed CAPA ${idx + 1} for audit ${audit._id}`,
    description: "Autogenerated seed CAPA for local testing.",
    severity: idx % 2 === 0 ? "major" : "minor",
    status: idx % 3 === 0 ? "IN_REVIEW" : "NEEDS_SUPPLIER",
    targetDate: new Date(Date.now() + (idx + 3) * 24 * 60 * 60 * 1000),
    createdBy: audit.create_by_buyer_id,
  }));

  await Capa.insertMany(docs);
  console.log(`Inserted ${docs.length} CAPA docs`);
}

seed()
  .then(() => mongoose.disconnect())
  .catch((err) => {
    console.error(err);
    mongoose.disconnect();
  });
